### PR TITLE
Search functionality on groomer screen

### PR DESCRIPTION
**Pull request by karinerafla**
1- Added a search functionality on the groomer screen. Focus on it when clicked on the search icon. Filters the groomers according to the name queried in the search bar.
Screenshot 2024-06-01 at 13 02 37
Screenshot 2024-06-01 at 13 03 35

2- Modified the colors on the modify address buttons to match the app

### CODE REVIEW

**Comment by Chocolat2** [comment]
Code looks great and works on my setup. 
Please resolve the merge conflicts

**Review by Chocolat2 — APPROVED** [review]

**Review by B6Amine — APPROVED** [review]
The functionality is working for me , the code seems writen well . U just need to resolve the conflicts now to be able to merge it . Nice work .

**Review by chtidaba — APPROVED** [review]
Conflicts are now resolved, search functionality is now implemented well, the Ui is pretty great.

**Review by Shinsaegae — COMMENTED** [review]
The code is very clean and the feature works very well.
Good job.

**Pull request merged**
