### PR TITLE
ktfmt-format

### PR DESCRIPTION
**Pull request by chtidaba**

### CODE REVIEW

**Review by chtidaba — COMMENTED** [review]
Now CI pass, Configured SonarCloud and successfully added it to the project

**Review by B6Amine — APPROVED** [review]
LGTM and approved

**Review by B6Amine — APPROVED** [review]

**Review by B6Amine — APPROVED** [review]
LGMT and approved

**Review by chtidaba — COMMENTED** [review]
LGTM

**Pull request merged**
